package systemd

import (
	"bytes"
)

// writeUnitFileService implements iSystemdService
func (s Systemd) writeUnitFileService(u UnitFileService, path string) error {
	// Marshal
	b := &bytes.Buffer{}
	// Add annotation to distinct generator
	b.WriteString("#! Generated by systemd-cd\n")
	if b2, err := MarshalUnitFile(u); err != nil {
		return err
	} else {
		b.Write(b2)
	}

	// Write to file
	err := writeFile(path, b.Bytes())
	if err != nil {
		return err
	}

	return nil
}
