package systemd

import (
	"bytes"
	"strings"
	"systemd-cd/domain/logger"
	"systemd-cd/domain/unix"
)

// loadUnitFileSerivce implements iSystemdService
func (s Systemd) loadUnitFileSerivce(path string) (u UnitFileService, isGeneratedBySystemdCd bool, err error) {
	logger.Logger().Debug("START - Load systemd unit file")
	logger.Logger().Debugf("< path = %v", path)
	defer func() {
		if err == nil {
			logger.Logger().Debugf("> unitFile.UnitDirective.Description = %v", u.Unit.Description)
			logger.Logger().Debugf("> isGeneratedBySystemdCd = %v", isGeneratedBySystemdCd)
			logger.Logger().Debug("END   - Load systemd unit file")
		} else {
			logger.Logger().Error("FAILED - Load systemd unit file")
			logger.Logger().Error(err)
		}
	}()

	// Read file
	b := &bytes.Buffer{}
	err = unix.ReadFile(path, b)
	if err != nil {
		return
	}

	// Check generator
	if strings.Contains(b.String(), "#! Generated by systemd-cd\n") {
		isGeneratedBySystemdCd = true
	}

	// Unmarshal
	u, err = UnmarshalUnitFile(b)
	if err != nil {
		return
	}

	return
}
