package systemd

import (
	"bytes"
	"systemd-cd/domain/logger"
)

// writeUnitFileService implements iSystemdService
func (s Systemd) writeUnitFileService(u UnitFileService, path string) error {
	logger.Logger().Trace(logger.Var2Text("Called", []logger.Var{{Value: u}, {Name: "path", Value: path}}))

	// Marshal
	b := &bytes.Buffer{}
	// Add annotation to distinct generator
	b.WriteString("#! Generated by systemd-cd\n")
	if b2, err := MarshalUnitFile(u); err != nil {
		logger.Logger().Error(logger.Var2Text("Error", []logger.Var{{Name: "err", Value: err}}))
		return err
	} else {
		b.Write(b2)
	}

	// Write to file
	err := writeFile(path, b.Bytes())
	if err != nil {
		logger.Logger().Error(logger.Var2Text("Error", []logger.Var{{Name: "err", Value: err}}))
		return err
	}

	logger.Logger().Trace("Finished")
	return nil
}
