package systemd

import (
	"bytes"
	"strings"
	"systemd-cd/domain/model/logger"
)

// loadUnitFileSerivce implements iSystemdService
func (s Systemd) loadUnitFileSerivce(path string) (u UnitFileService, isGeneratedBySystemdCd bool, err error) {
	logger.Logger().Trace(logger.Var2Text("Called", []logger.Var{{Name: "path", Value: path}}))

	// Read file
	b := &bytes.Buffer{}
	err = readFile(path, b)
	if err != nil {
		logger.Logger().Error(logger.Var2Text("Error", []logger.Var{{Name: "err", Value: err}}))
		return
	}

	// Check generator
	if strings.Contains(b.String(), "#! Generated by systemd-cd\n") {
		isGeneratedBySystemdCd = true
	}

	// Unmarshal
	u, err = UnmarshalUnitFile(b)
	if err != nil {
		logger.Logger().Error("Error:\n\tu: %v\n\tisGeneratedBySystemdCd: %v\n\terr: %v", u, isGeneratedBySystemdCd, err)
		return
	}

	logger.Logger().Trace(logger.Var2Text("Finished", []logger.Var{{Name: "isGeneratedBySystemdCd", Value: isGeneratedBySystemdCd}}))
	return
}
