package systemd

import (
	"bytes"
	"strings"
	"systemd-cd/domain/model/toml"
)

// loadEnvFile implements iSystemdService
func (s Systemd) loadEnvFile(path string) (e map[string]string, isGeneratedBySystemdCd bool, err error) {
	// Read file
	b := &bytes.Buffer{}
	err = readFile(path, b)
	if err != nil {
		return
	}

	// Check generator
	if strings.Contains(b.String(), "#! Generated by systemd-cd\n") {
		isGeneratedBySystemdCd = true
	}

	// Decode
	err = toml.Decode(b, &e)
	if err != nil {
		return
	}

	return
}
