package systemd

import (
	"bytes"
	"strings"
	"systemd-cd/domain/model/logger"
	"systemd-cd/domain/model/toml"
)

// loadEnvFile implements iSystemdService
func (s Systemd) loadEnvFile(path string) (e map[string]string, isGeneratedBySystemdCd bool, err error) {
	logger.Logger().Tracef("Called:\n\targ.path: %v", path)

	// Read file
	b := &bytes.Buffer{}
	err = readFile(path, b)
	if err != nil {
		logger.Logger().Errorf("Error:\n\terr: %v", err)
		return
	}

	// Check generator
	if strings.Contains(b.String(), "#! Generated by systemd-cd\n") {
		isGeneratedBySystemdCd = true
	}

	// Decode
	// TODO: toml format で問題ないか検証
	logger.Logger().Warn("Unchecked code: no problem to systemd service environment file with TOML format.")
	err = toml.Decode(b, &e)
	if err != nil {
		logger.Logger().Errorf("Error:\n\tisGeneratedBySystemdCd: %v\n\terr: %v", isGeneratedBySystemdCd, err)
		return
	}

	logger.Logger().Tracef("Finished:\n\te: %v\n\tisGeneratedBySystemdCd: %v", e, isGeneratedBySystemdCd)
	return
}
