package systemd

import (
	"bytes"
	"systemd-cd/domain/model/logger"
)

// writeUnitFileService implements iSystemdService
func (s Systemd) writeUnitFileService(u UnitFileService, path string) error {
	logger.Logger().Tracef("Called:\n\targ.u: %v\n\targ.path: %v", u, path)

	// Marshal
	b := &bytes.Buffer{}
	// Add annotation to distinct generator
	b.WriteString("#! Generated by systemd-cd\n")
	if b2, err := MarshalUnitFile(u); err != nil {
		logger.Logger().Errorf("Error:\n\terr: %v", err)
		return err
	} else {
		b.Write(b2)
	}

	// Write to file
	err := writeFile(path, b.Bytes())
	if err != nil {
		logger.Logger().Errorf("Error:\n\terr: %v", err)
		return err
	}

	logger.Logger().Tracef("Finished")
	return nil
}
