package systemd

import (
	"bytes"
	"systemd-cd/domain/model/toml"
)

// writeEnvFile implements iSystemdService
func (s Systemd) writeEnvFile(e map[string]string, path string) error {
	// Encode
	b := &bytes.Buffer{}
	// Add annotation
	b.WriteString("#! Generated by systemd-cd\n")
	indent := ""
	err := toml.Encode(b, e, toml.EncodeOption{Indent: &indent})
	if err != nil {
		return err
	}

	// Write to file
	err = writeFile(path, b.Bytes())

	return err
}
